nodeLinker: node-modules

packageExtensions:
  "@remix-run/cloudflare-pages@1.1.1":
    dependencies:
      react: "*"
      react-dom: "*"
  "@remix-run/dev@1.1.1":
    dependencies:
      "@remix-run/server-runtime": 1.1.1
      react: "*"
      react-dom: "*"
  wrangler@*:
    peerDependencies:
      cron-schedule: ^3.0.4

yarnPath: .yarn/releases/yarn-3.1.1.cjs
